// Dados do Linktree. Os endereços de checkout e os destinos vêm dos botões publicados em
// www.ineliagarcia.com (GreatPages), lidos em 01/10/2026. O `xcod` e o `_gl` congelados no HTML
// antigo NÃO vêm para cá: a origem passa a ser a UTM de cada botão.

export const SITE = {
  nome: "Inelia Garcia",
  handle: "@ineliagarcia",
  gtm: "GTM-5S4VC3BL",
  ga4: "G-62VEN9L651",
  rodape:
    "Studio de Exercícios · Rua Doutor Veiga Filho, 402 · São Paulo - SP · CEP 01229-000 · CNPJ 03.625.983/0001-40",
};

const wa = (num, txt) => `https://wa.me/${num}?text=${encodeURIComponent(txt)}`;

export const IDIOMAS = {
  br: {
    lang: "pt-BR",
    path: "link-br",
    prod: "link-bio-proutos-digitais",
    titulo: "Inelia Garcia",
    tagline: "Teacher of the Teachers",
    cookies: "Usamos cookies para personalizar conteúdos e melhorar a sua experiência.",
    ok: "Ok, entendi",
    botoes: [
      { id: "plataforma", texto: "Plataforma Autêntico Pilates", href: "@prod" },
      { id: "formacao-brasil", texto: "Formação Brasil 2027", href: "https://brasil.ineliagarcia.com/" },
      { id: "formacao-portugal", texto: "Formação Portugal 2027", href: "https://pilatesportugal.pt/certificacao-26-27/" },
      { id: "formacion-chile", texto: "Formación Chile 2027", href: "https://wa.me/56985282402" },
      { id: "loja", texto: "Loja Virtual", href: wa("5511989129767", "Olá,\n\nTenho interesse em adquirir um produto da loja do Pilates. Meu nome é...") },
      { id: "aparelhos", texto: "Comprar Aparelhos", href: wa("5511970778961", "\nOlá,\n\nTenho interesse em adquirir um equipamento da Joe Pilates. Meu nome é...") },
    ],
    produtos: {
      kicker_plat: "Plataforma Online",
      kicker_ws: "Workshop Gravado",
      saber: "Saber Mais",
      adquirir: "Adquirir",
      landing: "https://academybr.ineliagarcia.com",
      cards: [
        { id: "plataforma", kicker: "Plataforma Online", titulo: "Autêntico Pilates de Educação Continuada", img: "plataforma.jpg", destaque: true,
          txt: ["Aprenda a evoluir o corpo de QUALQUER aluno do básico ao avançado com segurança.", "Independente da sua saúde, do seu condicionamento físico ou da sua anatomia, através dos princípios do Autêntico Pilates."],
          href: "https://pay.hotmart.com/A73769458C?off=ri47wli4&checkoutMode=10" },
        { id: "pre-pilates-idosos", kicker: "Plataforma Online", titulo: "Pré Pilates para Idosos", img: "idosos.jpg",
          txt: ["Unindo os princípios do Autêntico Pilates a exercícios adaptados, essa abordagem promove força, flexibilidade, equilíbrio e bem-estar para idosos. Minimiza as limitações da idade e melhora a qualidade de vida no dia a dia."],
          href: "https://pay.hotmart.com/R76499789R" },
        { id: "alongamento-consciente", kicker: "Plataforma Online", titulo: "Alongamento Consciente", img: "alongamento.jpg",
          txt: ["Desenvolvido por Inelia Garcia, o Alongamento Consciente vai além do exercício: reeduca o movimento e transforma a conexão entre corpo, mente e propósito. Eleva suas aulas a um novo nível de personalização e impacto."],
          href: "https://pay.hotmart.com/X84155175J" },
        { id: "esencia-baby-chair", kicker: "Plataforma Online", titulo: "Esencia Baby Chair", img: "baby.jpg",
          txt: ["Focada em um dos aparelhos mais versáteis do método.", "Em uma abordagem modular e progressiva, você aprende não apenas a executar os movimentos, mas a compreender a filosofia e a ciência por trás de cada exercício. Isso transforma sua prática e seu ensino."],
          href: "https://pay.hotmart.com/U87161020R" },
        { id: "reformer-intermediario", kicker: "Workshop Gravado", titulo: "Reformer Intermediário", img: "reformer.jpg",
          txt: ["Técnicas avançadas no Reformer para construção do corpo e consciência corporal, com ênfase na postura do professor, uso do headson, detecção de erros e correções precisas."],
          href: "https://pay.hotmart.com/B91498288R?checkoutMode=10" },
        { id: "system", kicker: "Workshop Gravado", titulo: "System", img: "system.jpg",
          txt: ["Descubra como utilizar os aparelhos para desenvolver força, flexibilidade e resistência nos alunos, promovendo controle motor e consciência corporal para elevar os resultados no método."],
          href: "https://pay.hotmart.com/P91498511W?checkoutMode=10" },
        { id: "cadillac", kicker: "Workshop Gravado", titulo: "Cadillac", img: "cadillac.jpg",
          txt: ["Aprenda a utilizar o Cadillac para potencializar a evolução do aluno no método, com foco nos processos pedagógicos, hierarquia dos exercícios e construção da percepção e execução correta dos movimentos."],
          href: "https://pay.hotmart.com/M91498733T?checkoutMode=10" },
        { id: "mat", kicker: "Workshop Gravado", titulo: "Mat", img: "mat.jpg",
          txt: ["Estratégias práticas para instruir Mat em aulas grupais, com foco em pedagogia e personalização para maximizar o engajamento e os resultados dos alunos."],
          href: "https://pay.hotmart.com/M91499159A?checkoutMode=10" },
        { id: "treino-com-inelia", kicker: "Workshop Gravado", titulo: "Treino você e Inelia", img: "treino.jpg",
          txt: ["Uma aula prática de 4 horas com Inelia, onde você treina junto com ela e coloca em prática todo o conhecimento adquirido nos workshops anteriores, com orientação direta e personalizada."],
          href: "https://pay.hotmart.com/H91499437Y?checkoutMode=10" },
      ],
    },
  },
  es: {
    lang: "es",
    path: "link-esp",
    prod: "link-bio-produtos-digitais-esp",
    titulo: "Inelia Garcia",
    tagline: "Teacher of the Teachers",
    cookies: "Usamos cookies para personalizar contenidos y mejorar tu experiencia.",
    ok: "Ok, entendido",
    botoes: [
      { id: "plataforma", texto: "Estudia y Entrena con Inelia - 100% online.", href: "@prod" },
      { id: "formacion-brasil", texto: "Formación Presencial - 2027 - Brasil", href: "https://brasil.ineliagarcia.com/" },
      { id: "tienda", texto: "Tienda Virtual", href: wa("5511989129767", "Hola,\n\nEstoy interesado/a en adquirir un producto de la tienda de Pilates. Mi nombre es...") },
      { id: "equipos", texto: "Comprar Equipos", href: wa("5511970778961", "Hola,\n\nEstoy interesado/a en adquirir un equipo de Joe Pilates. Mi nombre es...") },
    ],
    produtos: {
      saber: "Saber Más",
      adquirir: "Adquirir",
      landing: "https://academyes.ineliagarcia.com",
      cards: [
        { id: "plataforma", kicker: "Plataforma Online", titulo: "Auténtico Pilates de Educación Continua", img: "plataforma.jpg", destaque: true,
          txt: ["Aprende a hacer evolucionar el cuerpo de CUALQUIER alumno, del nivel básico al avanzado, con seguridad.", "Independientemente de su salud, su condición física o su anatomía, a través de los principios del Auténtico Pilates."],
          href: "https://pay.hotmart.com/I96162102V?off=zispcw20&checkoutMode=10" },
        { id: "pre-pilates-adultos-mayores", kicker: "Plataforma Online", titulo: "Pre Pilates para Adultos Mayores", img: "idosos.jpg",
          txt: ["Uniendo los principios del Auténtico Pilates con ejercicios adaptados, este enfoque promueve fuerza, flexibilidad, equilibrio y bienestar para adultos mayores. Minimiza las limitaciones propias de la edad y mejora la calidad de vida en el día a día."],
          href: "https://pay.hotmart.com/B99031927K" },
        { id: "estiramiento-consciente", kicker: "Plataforma Online", titulo: "Estiramiento Consciente", img: "alongamento.jpg",
          txt: ["Desarrollado por Inelia Garcia, el Estiramiento Consciente va más allá del ejercicio: reeduca el movimiento y transforma la conexión entre cuerpo, mente y propósito. Lleva tus clases a un nuevo nivel de personalización e impacto."],
          href: "https://pay.hotmart.com/K99048700X" },
        { id: "esencia-baby-chair", kicker: "Plataforma Online", titulo: "Esencia Baby Chair", img: "baby.jpg",
          txt: ["Centrado en uno de los aparatos más versátiles del método.", "Con un enfoque modular y progresivo, aprenderás no solo a ejecutar los movimientos, sino a comprender la filosofía y la ciencia detrás de cada ejercicio. Esto transforma tu práctica y tu enseñanza."],
          href: "https://pay.hotmart.com/L95905690J?off=ub8im0ak" },
        { id: "reformer-intermediario", kicker: "Workshop Grabado", titulo: "Reformer Intermediario", img: "reformer.jpg",
          txt: ["Técnicas avanzadas en el Reformer para la construcción del cuerpo y la conciencia corporal, con énfasis en la postura del profesor, el uso de los headson, la detección de errores y correcciones precisas."],
          href: "https://pay.hotmart.com/A99095082K?off=9z4bksbn" },
        { id: "system", kicker: "Workshop Grabado", titulo: "System", img: "system.jpg",
          txt: ["Descubre cómo utilizar los aparatos para desarrollar fuerza, flexibilidad y resistencia en los alumnos, promoviendo el control motor y la conciencia corporal para elevar los resultados en el método."],
          href: "https://pay.hotmart.com/U99096516A?off=32m1bydg" },
        { id: "cadillac", kicker: "Workshop Grabado", titulo: "Cadillac", img: "cadillac.jpg",
          txt: ["Aprende a utilizar el Cadillac para potencializar la evolución del alumno en el método, con foco en los procesos pedagógicos, la jerarquía de los ejercicios y la construcción de la percepción y ejecución correcta de los movimientos."],
          href: "https://pay.hotmart.com/G99098561D" },
        { id: "mat", kicker: "Workshop Grabado", titulo: "Mat", img: "mat.jpg",
          txt: ["Estrategias prácticas para instruir Mat en clases grupales, con foco en pedagogía y personalización para maximizar el compromiso y los resultados de los alumnos."],
          href: "https://pay.hotmart.com/E99099114R" },
        { id: "entrena-con-inelia", kicker: "Workshop Grabado", titulo: "Entrena con Inelia", img: "treino.jpg",
          txt: ["Una clase práctica de 4 horas con Inelia, donde entrenas junto a ella y pones en práctica todo el conocimiento adquirido en los workshops anteriores, con orientación directa y personalizada."],
          href: "https://pay.hotmart.com/N99099432T" },
      ],
    },
  },
  en: {
    lang: "en",
    path: "link-eng",
    prod: "link-bio-produtos-digitais-eng",
    titulo: "Inelia Garcia",
    tagline: "Teacher of the Teachers",
    cookies: "We use cookies to personalize content and improve your experience.",
    ok: "Ok, got it",
    botoes: [
      { id: "plataforma", texto: "Study and Train with Inelia - 100% online.", href: "@prod" },
      { id: "formation-brazil", texto: "2027 In-Person Training in Brazil", href: "https://brasil.ineliagarcia.com/" },
      { id: "store", texto: "Online Store", href: wa("5511989129767", "Hello,\n\nI am interested in purchasing a product from the Pilates store. My name is...") },
      { id: "equipment", texto: "Purchase Equipment", href: wa("5511970778961", "Hello,\n\nI am interested in purchasing equipment from Joe Pilates. My name is...") },
    ],
    produtos: {
      saber: "Learn more",
      adquirir: "Get Access",
      landing: "https://academyen.ineliagarcia.com",
      cards: [
        { id: "plataforma", kicker: "Online Platform", titulo: "Authentic Pilates Continuing Education", img: "plataforma.jpg", destaque: true,
          txt: ["Learn how to evolve the body of ANY student, from beginner to advanced, safely.", "Regardless of their health, physical condition, or anatomy, through the principles of Authentic Pilates."],
          href: "https://pay.hotmart.com/P96110338W?off=2ja8tpn7&checkoutMode=10" },
        { id: "pre-pilates-seniors", kicker: "Online Platform", titulo: "Pre Pilates for Seniors", img: "idosos.jpg",
          txt: ["Combining the principles of Authentic Pilates with adapted exercises, this approach promotes strength, flexibility, balance, and well-being for older adults. It minimizes age-related limitations and improves everyday quality of life."],
          href: "https://pay.hotmart.com/W99036684N" },
        { id: "mindful-stretching", kicker: "Online Platform", titulo: "Mindful Stretching", img: "alongamento.jpg",
          txt: ["Developed by Inelia Garcia, Conscious Stretching goes beyond exercise: it re-educates movement and transforms the connection between body, mind, and purpose. It elevates your classes to a new level of personalization and impact."],
          href: "https://pay.hotmart.com/G99051415K" },
        { id: "esencia-baby-chair", kicker: "Online Platform", titulo: "Esencia Baby Chair", img: "baby.jpg",
          txt: ["Focused on one of the most versatile apparatus in the method.", "Through a modular and progressive approach, you will learn not only how to execute the movements, but how to understand the philosophy and science behind each exercise. This transforms your practice and your teaching."],
          href: "https://pay.hotmart.com/F95903899T" },
        { id: "intermediate-reformer", kicker: "Recorded Workshop", titulo: "Intermediate Reformer", img: "reformer.jpg",
          txt: ["Advanced techniques on the Reformer for body building and body awareness, with emphasis on teacher posture, use of headson, error detection, and precise corrections."],
          href: "https://pay.hotmart.com/P99114734A" },
        { id: "system", kicker: "Recorded Workshop", titulo: "System", img: "system.jpg",
          txt: ["Discover how to use the apparatus to develop strength, flexibility, and endurance in students, promoting motor control and body awareness to elevate results within the method."],
          href: "https://pay.hotmart.com/O99115530M" },
        { id: "cadillac", kicker: "Recorded Workshop", titulo: "Cadillac", img: "cadillac.jpg",
          txt: ["Learn how to use the Cadillac to maximize student progress in the method, with a focus on pedagogical processes, exercise hierarchy, and building correct perception and execution of movements."],
          href: "https://pay.hotmart.com/N99116969W" },
        { id: "mat", kicker: "Recorded Workshop", titulo: "Mat", img: "mat.jpg",
          txt: ["Practical strategies for teaching Mat in group classes, with a focus on pedagogy and personalization to maximize student engagement and results."],
          href: "https://pay.hotmart.com/X99117503B" },
        { id: "train-with-inelia", kicker: "Recorded Workshop", titulo: "Train with Inelia", img: "treino.jpg",
          txt: ["A 4-hour hands-on class with Inelia, where you train alongside her and put into practice all the knowledge gained in the previous workshops, with direct, personalized guidance."],
          href: "https://pay.hotmart.com/U99117853A" },
      ],
    },
  },
};
